@startuml Add Book Sequence

skinparam sequence {
    ParticipantBackgroundColor LightBlue
    ParticipantBorderColor Black
    LifeLineBackgroundColor LightGray
}

actor User
participant "LibraryGUI" as GUI
participant "LibraryController" as Controller
participant "AddBookDialog" as Dialog
participant "AddBookCommand" as Command
participant "LibrarySingleton" as Singleton
participant "Library" as Lib
participant "JsonHandler" as Json
participant "BookTableModel" as Model

activate GUI
User -> GUI: click "Aggiungi"

GUI -> Dialog: new AddBookDialog()
activate Dialog
GUI -> Dialog: showDialog()

User -> Dialog: inserisce dati libro
Dialog --> GUI: return newBook
deactivate Dialog

GUI -> Controller: addBook(newBook)
activate Controller

Controller -> Command: new AddBookCommand(library, newBook)
activate Command

Controller -> Command: execute()
Command -> Singleton: addBook(newBook)
activate Singleton

Singleton -> Lib: addBook(newBook)
activate Lib
Lib --> Singleton: success
deactivate Lib

Singleton --> Command: success
deactivate Singleton

Command --> Controller: success
deactivate Command

Controller -> Singleton: saveBooksToJson(file)
activate Singleton
Singleton -> Json: saveBooks(file, books)
activate Json
Json --> Singleton: success
deactivate Json
Singleton --> Controller: success
deactivate Singleton
Controller --> GUI: success
deactivate Controller

GUI -> GUI: loadBooks()
activate GUI
GUI -> Singleton: getLibrary().getBooks()
activate Singleton
Singleton --> GUI: books list
deactivate Singleton

GUI -> Model: setBooks(books)
activate Model
Model --> GUI: success
deactivate Model

GUI --> User: aggiorna vista
deactivate GUI
deactivate GUI

@enduml
