@startuml Search Sequence Diagram
'https://plantuml.com/sequence-diagram

skinparam sequence {
    ParticipantBackgroundColor LightBlue
    ParticipantBorderColor Black
    LifeLineBackgroundColor LightGray
}

actor User
participant "LibraryGUI" as GUI
participant "LibraryController" as Controller
participant "SearchDialog" as Dialog
participant "SearchFilter" as Filter
participant "SearchStrategy" as Search
participant "FilteredSearchStrategy" as FilteredSearch
participant "LibrarySingleton" as Singleton
participant "Library" as Library

activate GUI
User -> GUI: click "Cerca"

GUI -> Dialog: new SearchDialog(this)
activate Dialog
User -> Dialog: inserisce dati ricerca
Dialog -> GUI: return searchFilter
deactivate Dialog

GUI --> Controller: searchBooks(filter)
activate Controller

alt filter != null
    Controller -> Filter: isSearchByTitle()
    alt searchByTitle == true
        Controller -> Search: new TitleSearchStrategy()
    else searchByTitle == false
        Controller -> Search: new AuthorSearchStrategy()
    end

    Controller -> FilteredSearch: new FilteredSearchStrategy(baseStrategy,\n readingStatusFilter, minRating)

    activate FilteredSearch
    Controller -> FilteredSearch: search(books, searchTerm)
    FilteredSearch --> Controller: risultati filtrati
    deactivate FilteredSearch

    Controller --> GUI: ritorna lista di risultati
else
    Controller --> GUI: ritorna null
end


Controller --> Strategy: sort(library.getBooks())
activate Strategy
Strategy --> Controller: success
deactivate Strategy

Controller --> GUI: return sorted
deactivate Controller

GUI --> Model: new BookTableModel(sorted)
activate Model
Model --> GUI: return model
deactivate Model

GUI --> GUI: bookTable.setModel(model);
activate GUI
deactivate GUI

GUI --> User: aggiorna vista
deactivate GUI

@enduml