@startuml Library Component Diagram
'https://plantuml.com/component-diagram

skinparam component {
  BackgroundColor<<UI>> LightBlue
  BackgroundColor<<Controller>> LightGreen
  BackgroundColor<<Model>> LightYellow
  BackgroundColor<<Utility>> LightGray
}

package "GUI" {
  [LibraryGUI]<<UI>>
  [SearchDialog]<<UI>>
  [AddBookDialog]<<UI>>
  [UpdateBookDialog]<<UI>>
  [BookTableModel]<<UI>>
}

package "Controller" {
  [LibraryController] <<Controller>>
}

package "Singleton" {
  [LibrarySingleton] <<Singleton>>
}

package "Model" {
  [Library]<<Model>>
  [Book]<<Model>>
  [SearchFilter]<<Model>>


}

package "Command" {
  [AddBookCommand]<<Controller>>
  [DeleteBookCommand]<<Controller>>
  [UpdateBookCommand]<<Controller>>
}

package "Strategy" {
  [SearchStrategy]<<Utility>>
  [SortStrategy]<<Utility>>
}

package "Singleton" {
  [LibrarySingleton]<<Utility>>
}

package "Utile" {
  [JsonHandler]<<Database>>
}

' Relazioni

LibraryGUI --> LibraryController

LibraryGUI --> AddBookDialog
LibraryGUI --> UpdateBookDialog
LibraryGUI --> SearchDialog
LibraryGUI --> BookTableModel
LibraryGUI --> LibrarySingleton

LibrarySingleton --> JsonHandler
LibrarySingleton --> Library
Library --> Book

AddBookCommand --> LibrarySingleton
DeleteBookCommand --> LibrarySingleton
UpdateBookCommand --> LibrarySingleton

LibraryController --> AddBookCommand
LibraryController --> DeleteBookCommand
LibraryController --> UpdateBookCommand

LibraryController --> SearchStrategy
LibraryController --> SortStrategy

BookTableModel --> Book

@enduml
