@startuml Singleton Component Diagram

skinparam class {
    BackgroundColor<<Singleton>> LightBlue
    BackgroundColor<<Template>> LightGreen
}

package "Singleton" {
    class LibrarySingleton <<Singleton>> {
        - {static} instance: LibrarySingleton
        - library: Library
        - searchStrategy: SearchStrategy
        - sortStrategy: SortStrategy
        - LibrarySingleton()
        + {static} getInstance(): LibrarySingleton
        + getLibrary(): Library
        + addBook(Book) : void
        + removeBook(isbn: String)
        + updateBook(Book) : void
        + loadBooksFromJson(File): void
        + saveBooksToJson(File): void
        + setSearchStrategy(SearchStrategy): void
        + setSortStrategy(SortStrategy): void
        + search(List<Book>, String): List<Book>
        + sort(List<Book>): List<Book>
    }
}

@enduml