@startuml Singleton Component Diagram

skinparam class {
    BackgroundColor LightBlue
}

package "Singleton" {
    class LibrarySingleton {
        - {static} instance: LibrarySingleton
        - library: Library
        - jsonFile: File
        - LibrarySingleton()
        + {static} getInstance(): LibrarySingleton
        + getLibrary(): Library
        + setSource(jsonFile: File): void
        + addBook(Book): void
        + removeBook(isbn: String): void
        + updateBook(Book): void
        + loadBooksFromJson(File): void
        + saveBooksToJson(File): void
    }
}

@enduml