@startuml Util Diagram

skinparam class {
    BackgroundColor LightGray
}

package "util" {

    class JsonHandler {
        - {static} mapper: ObjectMapper
        + {static} loadBooks(File): List<Book>
        + {static} saveBooks(File, List<Book>): void
    }

    class LibraryController {
    + LibraryController()
    + getAllBooks(): List<Book>
    + addBook(newBook: Book): void
    + updateBook(updatedBook: Book): void
    + removeBook(isbn: String): void
    + searchBooks(filter: SearchFilter): List<Book>
    + sortBooks(strategy: SortStrategy): List<Book>
    + save(): void
    }
}

@enduml
